name: to_do_app
description: "A new Flutter project."

publish_to: 'none'  

 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

 
dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.1


   
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

   
  flutter_lints: ^3.0.0

 
flutter:

  
  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/static/Raleway-Thin.ttf
          weight: 100
        - asset: assets/fonts/static/Raleway-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/static/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/static/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/static/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/static/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/static/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/static/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/static/Raleway-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/static/Raleway-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/static/Raleway-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/static/Raleway-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/static/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/static/Raleway-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/static/Raleway-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/static/Raleway-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/static/Raleway-BlackItalic.ttf
          weight: 900
          style: italic
  
